# Generated by Django 3.1.1 on 2020-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
