# Generated by Django 3.1.1 on 2020-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stype',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='stype',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
