# Generated by Django 3.1.1 on 2020-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200926_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='readytodeliver',
            field=models.BooleanField(),
        ),
    ]
