# Generated by Django 3.1.1 on 2020-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200921_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicedate',
            field=models.DateField(),
        ),
    ]
