# Generated by Django 3.1.1 on 2020-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200926_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manufacturer',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='vehiclenum',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
