# Generated by Django 3.1.1 on 2020-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200926_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='readytodeliver',
            field=models.BooleanField(default=False),
        ),
    ]
